# Generated by Django 2.0.3 on 2018-05-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profilep_pic',
            new_name='profile_pic',
        ),
    ]
